// <auto-generated />
namespace DentalClinic.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Core_Schema_created : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Core_Schema_created));
        
        string IMigrationMetadata.Id
        {
            get { return "201711131845545_Core_Schema_created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
